### ISSUE TITLE
Getting error Service-b deployment

### ISSUE THREAD

**Issue by dotnetstep** [dgkanatsios/acsk8svstsdemo#1]
I have applied all steps. I am getting error like following
```

2018-06-22T05:32:38.8117343Z ##[error]The Deployment "service-b-deployment" is invalid: 
2018-06-22T05:32:38.8822623Z ##[error]* spec.selector: Required value
2018-06-22T05:32:38.9579684Z ##[error]* spec.template.metadata.labels: Invalid value: map[string]string{"app":"demo", "name":"service-b"}: `selector` does not match template `labels`
2018-06-22T05:32:39.0438744Z ##[error]/usr/local/bin/kubectl failed with return code: 1
```

My yaml file. // 

```
apiVersion: v1
kind: Pod
metadata:
  name: service-a
  labels:
    name: service-a
    app: demo
spec:
  containers:
  - name: service-a
    image: <<myazure registry>>/service-a:15
    ports:
    - containerPort: 80
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b-deployment
  labels:
    name: service-b
    app: demo
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        name: service-b
        app: demo
    spec:
      containers:
      - name: service-b
        image: <<myazure registry>>/service-b:15
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: mycache
  labels:
    name: mycache
    app: demo
spec:
  containers:
  - name: mycache
    image: redis:alpine
    ports:
    - containerPort: 6379
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: service-a-k8sservice
  labels:
    name: service-a
    app: demo
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: service-a
    app: demo
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: service-b-k8sservice
  labels:
    name: service-b
    app: demo
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: service-b
    app: demo
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: mycache-k8sservice
  labels:
    name: mycache
    app: demo
spec:
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
      protocol: TCP
  selector:
    name: mycache
    app: demo
  type: NodePort

```

**Comment by dotnetstep** [comment]
I am able to solve the issue and if required it can be done in this repository as well.

I have added selector.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b-deployment
  labels:
    name: service-b
    app: demo
spec:
  strategy:
    type: Recreate
  replicas: 3
  selector:
    matchLabels:
      name: service-b
      app: demo
  template:
    metadata:
      labels:
        name: service-b
        app: demo
    spec:
      containers:
      - name: service-b
        image: $ACR_DNS/service-b:$BUILD_ID
        ports:
        - containerPort: 80
          protocol: TCP
```
